export = TreeView;
declare class TreeView {
    constructor(id: any);
    _init(): void;
    baseClass: string;
    items: any[];
    itemsOrder: any[];
    binsOrder: any[];
    defaults(): void;
    width: number;
    height: number;
    set multiselect(arg: any);
    get multiselect(): any;
    binsView: any;
    itemsView: any;
    clear(): void;
    selected: any[];
    _events(): void;
    onDragOver: (e: any) => void;
    currentCover: string;
    onDrop: (e: any) => void;
    currentBin: any;
    onMouseDown: (e: any) => void;
    mouseDown: boolean;
    onMouseUp: (e: any) => void;
    refreshOrder(): void;
    getOrder(): any[];
    reorder(dropUid: any): void;
    clearSelection(uid: any, forced: any): void;
    addBin(obj: any): any;
    addItem(obj: any): any;
    _add(obj: any): any;
    removeSelected(): void;
    remove(uid: any): void;
    updateTree(): void;
    orderedItems: any[];
    sift(parent: any, all: any): any[];
    renderBin(parent: any, ident: any, itemsOnly: any): void;
    set iconOpen(arg: any);
    get iconOpen(): any;
    set iconClosed(arg: any);
    get iconClosed(): any;
    set iconEmpty(arg: any);
    get iconEmpty(): any;
    set captionWidthRem(arg: any);
    get captionWidthRem(): any;
    set onSelect(arg: any);
    _onSelect: any;
    set onDropped(arg: any);
    _onDrop: any;
    set onRemove(arg: any);
    _onRemove: any;
    set binMode(arg: any);
    get binMode(): any;
    _view: any;
    store(): any[];
    restore(arr: any): void;
}
