export const gSelectorTable: any[];
export const log: {
    (...data: any[]): void;
    (message?: any, ...optionalParams: any[]): void;
};
export const gListOfCssRules: any[];
export const alNone: "alNone";
export const alClient: "alClient";
export const alTop: "alTop";
export const alRight: "alRight";
export const alBottom: "alBottom";
export const alLeft: "alLeft";
export const anTopLeft: "anTopLeft";
export const anTop: "anTop";
export const anTopRight: "anTopRight";
export const anRight: "anRight";
export const anBottomRight: "anBottomRight";
export const anBottom: "anBottom";
export const anBottomLeft: "anBottomLeft";
export const anLeft: "anLeft";
export function getId(sTag: any): HTMLElement;
export function crEl(k: any, opt: any, parent: any): any;
export function crDiv(opt: any, parent: any): any;
export function CtrlCmd(e: any): any;
export function DeepCopy(obj: any): any;
export function numberToPx(v: any): any;
export function pxToNumber(v: any): number;
export function computedStyleToNumber(element: any, style: any): number;
export function setCssAdv(selector: any, value: any): void;
export function getListOfCssRules(): any[];
export function listCssRules(cssRule: any): void;
export function findCssRule(cssRule: any, selector: any): any;
export function getComputedCSSStyle(className: any, styleName: any): number;
export function resetApp(): void;
export function rnd(max: any): number;
export function firstLetterUpper(name: any): any;
export function firstLetterLower(name: any): any;
export function boxOverlap(a: any, b: any): any;
export function ch(): void;
