export default class ListView extends Component {
    constructor(id: any);
    _init(): void;
    rowHeightPx: number;
    splitV: Container3;
    headerRow: Panel;
    splitH: Container2;
    table: any;
    items: any[];
    _options: {};
    multiselect: any;
    scrollV: any;
    scrollH: any;
    defaults(): void;
    rowTop: number;
    topItem: any;
    columns: any[];
    selected: any[];
    autoClearSelection: boolean;
    set rowHeight(arg: any);
    get rowHeight(): any;
    _events(): void;
    handleDown: any;
    listMouseDown: boolean;
    _lastIndex: any;
    touchY: any;
    onResize: () => void;
    addResizeObserver(): void;
    resizeObserver: ResizeObserver;
    selectRange(a: any, b: any): void;
    onDblClick(): void;
    getSelected(): {
        index: any;
        columns: any;
    }[];
    getIndex(e: any): any;
    getItem(itemidx: any): any;
    select(itemidx: any): void;
    performSelect(itemidx: any): void;
    clearSelection(): void;
    wheel(dy: any, isset: any): void;
    update(): void;
    updateScrollBars(): void;
    _onResizeUpdate(): void;
    setHeaderColumns(): void;
    scrollWidth: number;
    fillTable(): void;
    tableInit(): void;
    visibleRows: number;
    set header(arg: any[]);
    get header(): any[];
    set options(arg: {});
    get options(): {};
    sortable: any;
    add(arr: any): void;
    clear(): void;
    get count(): number;
}
import Component from "../Component/Component";
import Container3 from "../Container3/Container3";
import Panel from "../Panel/Panel";
import Container2 from "../Container2/Container2";
